project_id = "${SUPABASE_PROJECT_REF}"

[api]
enabled = true

[db]
port = 6543
shadow_port = 6544

[functions.chat-api]
verify_jwt = true

[functions.booking-api]
verify_jwt = false

[functions.lead-gen-api]
verify_jwt = false
